# Generated by Django 4.1.6 on 2023-02-08 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coursecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_students', models.CharField(max_length=65, null=True)),
                ('courselecturers', models.ManyToManyField(to='base.course_lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_time', models.CharField(choices=[('8:00 - 10:00', '8:00 - 10:00'), ('10:00 - 12:00', '10:00 - 12:00'), ('12:00 - 02:00', '12:00 - 02:00'), ('02:00 - 04:00', '02:00 - 04:00'), ('04:00 - 06:00', '04:00 - 06:00')], default=('8:00 - 10:00', '8:00 - 10:00'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lectureroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coursecodes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.coursecode')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15, null=True)),
                ('number_of_classes_in_week', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coursecode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.coursecode')),
                ('courselecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course_lecturer')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lectureroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lectureroom')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.level')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.school')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.semester')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.time')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
